apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnjavaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnjavaapp
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "true" 
      labels:
        app: vulnjavaapp
    spec:
      securityContext:
        runAsNonRoot: true 
        allowPrivilegeEscalation: false
      containers:
        - name: vulnerable-java-app
          image: ghcr.io/datadog/vulnerable-java-application:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: vulnjavaapp-service
spec:
  type: LoadBalancer
  selector:
    app: vulnjavaapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
