apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnjavaapp
  labels:
    app: vulnjavaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnjavaapp
  template:
    metadata:
      labels:
        app: vulnjavaapp
    spec:
      containers:
      - name: vulnerable-java-app
        image: ghcr.io/datadog/vulnerable-java-application:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vulnjavaapp-service
spec:
  type: LoadBalancer
  selector:
    app: vulnjavaapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
