name: Deploy Datadog App to EKS

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_NAME: ghcr.io/datadog/vulnerable-java-application:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Limpar ambiente anterior
        run: |
          kubectl delete deployment vulnjavaapp --ignore-not-found
          kubectl delete service vulnjavaapp-service --ignore-not-found

      - name: Deploy to EKS using public Datadog image
        run: |
          kubectl set image deployment/vulnjavaapp \
            ${{ secrets.CONTAINER_NAME }}=${{ env.IMAGE_NAME }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/vulnjavaapp
