name: Deploy vulnerable-java-app to EKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/datadog/vulnerable-java-application:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Atualizar kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deletar ambiente anterior (opcional)
        run: |
          kubectl delete deployment vulnjavaapp --ignore-not-found
          kubectl delete service vulnjavaapp-service --ignore-not-found

      - name: Criar novo deployment com imagem do Datadog
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: vulnjavaapp
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: vulnjavaapp
            template:
              metadata:
                labels:
                  app: vulnjavaapp
              spec:
                containers:
                - name: vulnerable-java-app
                  image: ${IMAGE_NAME}
                  ports:
                  - containerPort: 8000
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: vulnjavaapp-service
          spec:
            type: LoadBalancer
            selector:
              app: vulnjavaapp
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8000
          EOF

      - name: Aguardar rollout do deployment
        run: kubectl rollout status deployment/vulnjavaapp